### ISSUE TITLE
Ошибка при сборке Обычных форм

### ISSUE THREAD

**Issue by HaSHsss** [saby-integration/v8unpack#10]
В у меня нашлись 2 формы которые не собираются из-за ошибки
Ожидается что есть `page['info']` но почему-то он у меня отсутствует
так и не понял что это и на что влияет, но без этих данных обработка собирается не корректно. Ошибка формата потока.

Из то го что заметил, то что проблемные формы имею несколько страниц на форме (5-8 шт). 
![image](https://github.com/saby-integration/v8unpack/assets/63124812/f9a1bc74-f1fe-4792-981a-8e964597a3f2)

![image](https://github.com/saby-integration/v8unpack/assets/63124812/05d1ea00-3822-4989-a639-4ef360daf446)

**Comment by businka** [comment]
исправил. используйте или старый стабильный 0.12.11 или новую 0.18.0
