### ISSUE TITLE
"Не удалось определить парсер" при распаковке кофигурации версии 8.2

### ISSUE THREAD

**Issue by user7** [saby-integration/v8unpack#49]
Приветствую!

ОС: Window 10 x64
Питон: python 3.11 для windows с оф сайта
v8unpack: 0.12.0, установлен через pip install v8unpack
Пытаюсь распаковать test.cf -- выгрузку рабочей конфигурации 1С: Предприятие 8.2

Чтобы обойти ошибку JSONDecodeError из https://github.com/saby-integration/v8unpack/issues/48 делаю описанный там "фикс", потом запускаю:

```
import v8unpack
if __name__ == '__main__':
    v8unpack.extract('test.cf', 'unpack', temp_dir = 'tmp')
```

и получаю:

```
v8unpack 0.12.0
Начали
Распаковываем бинарник        :0:00:17.386168
Распаковываем контейнеры      : 100%|██████████████████████████████████| 33023/33023 [03:10<00:00, 173.80it/s]
Конвертируем скобкофайл в json: 100%|██████████████████████████████████| 38132/38132 [02:22<00:00, 267.39it/s]
Разбираем объект


ExtException Unknown Error - Не удалось определить парсер
 Stack:
  - None: message=Exception; detail=Не удалось определить парсер; traceback=v8unpack/v8unpack.py, extract, line 80;
```

Похоже, что не срабатывает Decoder.detect_version:
```
    def detect_version(src_dir):
        if os.path.isfile(os.path.join(src_dir, 'root.json')):
            version = helper.json_read(src_dir, 'version.json')
            ...
        raise Exception('Не удалось определить парсер')
```
Пытался добавить при вызове version="802", не помогает. Судя по коду проблема в отсутствии файлов tmp/decode_stage_2/root.json и version.json. Что это за файлы и кто их должен создавать?

**Comment by businka** [comment]
вероятно у вас совсем пустая конфа без ресурсов. если так то вероятно этот сценарий не предусмотрел. добавьте в неё что нить. если не пустая - можете файл предоставить для анализа?

**Comment by user7** [comment]
Конфа взята с рабочего 1с предприятия, она не пустая. Секретного там ничего нет, могу приложить, но объём 308 мегабайт. Загружать?

**Comment by businka** [comment]
пустая, имелось ввиду новая. очень древняя конфа, много ресурсов тянется с 8.1.
сделал ветку 0.13.0 в которой она более менее разбирается, со сборкой есть проблемы. 
если разберетесь и  докините недостающее будет супер, будут вопрос в телеге есть одноименная группа

чтобы понять что все хорошо собирается и разбирается у Вас должен проходить тест \tests\Configuration802\test_decode_c802.py

**Comment by user7** [comment]
Спасибо, попробую.
