### ISSUE TITLE
Не разбирается cf

### ISSUE THREAD

**Issue by leobrn** [saby-integration/v8unpack#55]
Привет. Пробую разобрать cf файл, скачал exe файл с главной. На выходе получаю папку Language и файл Configuration.json
![1](https://user-images.githubusercontent.com/16267179/233286682-70009e8b-deea-4c69-834c-a0923a68c2ef.png)
![2](https://user-images.githubusercontent.com/16267179/233286688-3336928a-6602-4fb0-b5db-420923abc0c0.png)

**Comment by huxuxuya** [comment]
Версия платформы: 8.3.23.1596
v8unpack: 0.13.2
![изображение](https://user-images.githubusercontent.com/29693463/233998495-fe0096eb-d9ee-4cc9-b8fc-2532a9854e1a.png)
![изображение](https://user-images.githubusercontent.co
[apam.zip](https://github.com/saby-integration/v8unpack/files/11310500/apam.zip)
m/29693463/233998574-2ebcffdf-ca3a-4138-a377-ca9d7540f088.png)

В конфигурации есть модули:
![изображение](https://user-images.githubusercontent.com/29693463/233998835-56db11c5-de96-43e2-935d-74519c07d492.png)

**Comment by businka** [comment]
https://github.com/saby-integration/v8unpack/tree/support_8_3_16_format
сюда закидываю всё, пока нет возможности проверить.
какая это платформа?

**Comment by businka** [comment]
0.13.3
