### ISSUE TITLE
Не разбирается CF (старый формат цф)

### ISSUE THREAD

**Issue by huxuxuya** [saby-integration/v8unpack#56]
![изображение](https://user-images.githubusercontent.com/29693463/234199688-52db5116-b183-406f-8681-3da4c96bffa1.png)

**Comment by businka** [comment]
без примера не починить

**Comment by businka** [comment]
нужен cf на котором можно повторить проблему

**Comment by huxuxuya** [comment]
Не разбирается тип - графическая схема, на ней падает - 
[apam_add_schema_old.zip](https://github.com/saby-integration/v8unpack/files/11335634/apam_add_schema_old.zip)
![изображение](https://user-images.githubusercontent.com/29693463/234653049-fba0a021-2b2f-4dcc-910f-f661fe425ce1.png)

**Comment by businka** [comment]
https://github.com/saby-integration/v8unpack/tree/support_8_3_16_format
сюда закидываю всё, пока нет возможности проверить.

**Comment by businka** [comment]
0.13.3
