### ISSUE TITLE
Не разбирается CF (WSReference)

### ISSUE THREAD

**Issue by huxuxuya** [saby-integration/v8unpack#57]
![изображение](https://user-images.githubusercontent.com/29693463/234220992-4e4aa758-3b48-4d33-89f0-44bbdb7fd917.png)

**Comment by businka** [comment]
без проблемного файла никак не починить

**Comment by businka** [comment]
нужен cf на котором можно повторить проблем

**Comment by businka** [comment]
чтобы исправить добавьте в классе атрибут ext_code. я добавлю это в версию с новым форматом.
```
class WSReference(Simple):
    ext_code = {}
```
Чтобы поддержать тип метаданных Bot (у меня нет платформы где такое есть, это какую версию надо?)
напишите мне английское название метаданных ( в помощнике можно посмотреть)
и приложите премер конфы, где будет бот и в каждом типе кода (модуль объекта и т.п.) будет как минимум одна строчка с название что за код,  -  в модуле объекта комментарий "Код модуля объекта"

сам файл конфы крайне кривой, если это какой то конвертер, то он как то не правильн работает.

**Comment by businka** [comment]
https://github.com/saby-integration/v8unpack/tree/support_8_3_16_format
сюда закидываю всё, пока нет возможности проверить.
