### ISSUE TITLE
Возможность сохранять файлы в формате bsl

### ISSUE THREAD

**Issue by leobrn** [saby-integration/v8unpack#62]
Можно ли сделать возможность сохранять файлы в формате .bsl? Например функционально через доп. опцию --format BSL

`v8unpack.exe -E 1Cv8.cf src --format BSL`

Например в vs code будет сразу доступна подсветка синтаксиса и возможность проверки через 
[bsl-language-server](https://github.com/1c-syntax/bsl-language-server). Также удобно будет использовать для sonarqube/git
![image](https://github.com/saby-integration/v8unpack/assets/16267179/ace4faf8-2ade-4023-9f2c-42ae72f08698)

**Comment by businka** [comment]
технически нет никакой проблемы, весь вопрос чтобы всем было понятно что файл с таким расширением содержит код 1С. я никогда не сталкивался с bsl и не знаю насколько это популярно. кроме этого продукта это расширение где то ещё используется?

**Comment by leobrn** [comment]
> технически нет никакой проблемы, весь вопрос чтобы всем было понятно что файл с таким расширением содержит код 1С. я никогда не сталкивался с bsl и не знаю насколько это популярно. кроме этого продукта это расширение где то ещё используется?

Это расширение использует сама 1С, она выгружает в таком формате исходники, файлы в которых содержится код имеют расширение bsl

**Comment by businka** [comment]
0.15.0
