### ISSUE TITLE
Ограничение на многопоточность

### ISSUE THREAD

**Issue by leobrn** [saby-integration/v8unpack#63]
Нужна возможность указать ограничение на потоки т.к сейчас проц грузится по максимуму:
![image (11)](https://github.com/saby-integration/v8unpack/assets/16267179/fc33a4a7-7442-4c49-8a24-4b3c465ffbc0)
![image (12)](https://github.com/saby-integration/v8unpack/assets/16267179/7de6ebe5-2b05-423a-b2f5-276907c74b1d)
После выполнения нагрузка падает до нормы:
![image (13)](https://github.com/saby-integration/v8unpack/assets/16267179/d178b26f-619b-426a-8229-070a946ced8d)

**Comment by businka** [comment]
0.15.0 добавил опцию processes
