### ISSUE TITLE
Не разбирается .epf через python

### ISSUE THREAD

**Issue by arXXXimed** [saby-integration/v8unpack#69]
не разбирается .epf через python. ошибка 
```
ExtException Unknown Error - 'NoneType' object does not support item assignment
 Stack:
  - None: message=TypeError; detail='NoneType' object does not support item assignment; traceback=v8unpack/v8unpack.py, extract, line 53;
```

**Comment by businka** [comment]
приложите пример файла и строки вызова

**Comment by businka** [comment]
в папке test есть примеры

**Comment by arXXXimed** [comment]
```
import v8unpack

sourse = 'E:/PythonProject/ВнешняяОбработка803.epf'
dest = 'E:/PythonProject/dest'


if __name__ == '__main__':
    v8unpack.extract(sourse, dest)

```
Код взял из описания. Пробовал на разных версиях python. доходит до того как  консоль пишет: "Разбираем объект". Далее вываливается ошибка выше.

**Comment by arXXXimed** [comment]
На другом компьютере под windows, такая же ошибка. пакет был установлен через pip

**Comment by businka** [comment]
да. у меня повторилось. ошибка возникает когда не указан ни один доп. параметр. поправил в 0.15.4
