### ISSUE TITLE
Ошибка при сборке

### ISSUE THREAD

**Issue by HaSHsss** [saby-integration/v8unpack#7]
Благодарю за ваши старания.  Очень интересная работа.

У меня на последней версии 0.17.6 при сборке возникает ошибка

`Z:\git\v8unpack>v8unpack.exe -B unpack AA45_2.epf
v8unpack 0.17.6
Начали
Собираем код
Собираем код из файлов        : 100%|████████████████████████████████████████████████████| 2/2 [00:00<00:00, 10.42it/s]
Собираем элементы форм        : 100%|████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Собираем код - готово         : 0:00:00.209996
Собираем объект
Собираем вложенные объекты    :   0%|                                                            | 0/1 [00:00<?, ?it/s]

```
ExtException Ошибка при сборке формы - Form C:\Users\HaSHs\AppData\Local\Temp\tmpl7xzs1q4\encode_stage_3\Form\Форма
 Stack:
  - None: message=IndexError; detail=string index out of range; traceback=Form802Elements/Form27.py, encode, line 95;
  - Form803.encode:
  - Decoder.encode_include(Form):`
```
  
  
[AA45.zip](https://github.com/saby-integration/v8unpack/files/14102893/AA45.zip)

**Comment by HaSHsss** [comment]
С этим файлом разобрался
без указания --version 802
Обычные формы пытались собраться как Управляемые.

Теперь другой вопрос

У меня есть обработка где есть и обычные и управляемые формы
Он при сборке спотыкается либо об один вид формы либо об другой в зависимости от version

Как мне собрать такое проект?

**Comment by businka** [comment]
это ошибка. без указания версии или с 803 должно собираться. поправлю в 0.18

**Comment by businka** [comment]
поправил. проверил на чем смог
